function [ false_positive_test, true_positive_test, res_test] = test_model( SVMModel, nbrOfSamples ,target_freq,mean_train, std_train)
[nposfilestest,nnegfilestest,samplestest] = parse_acc_files(nbrOfSamples * 2,'acc_data\freq400temp\postest\acc*' ...
, 'acc_data\freq400temp\negtest\acc*');
[samplestest, ~] = convert_freq(samplestest,400,target_freq);
nbrfilestest = nposfilestest + nnegfilestest;

[meanFeatures, maxFeatures, minFeatures, kurtosis_vec, skewness_vec, sumFeatures, ...
    meanTiltFeatures, stdFeatures, stdTiltFeatures, sumAllDimFeatures, maxTiltFeatures, ...
    minTiltFeatures, der_mean, der_max, der_min, der_sum, moments,sum_changes, mean_changes, ...
    sumAbsFeatures, index_of_first_max, index_of_first_min] = extract_base_features( samplestest,nbrOfSamples,nbrfilestest );

[ psdx_peak_power_ratio, psdx_peak_power_ratio_tilt, psdx_peak_freq_bin, psdx_peak_freq_bin_tilt, psdx_nbrPeaks_tilt, ...
    psdx_nbrPeaks,psdx_mean, psdx_max, psdx_min,psdx_sum, psdx_tilt_mean, psdx_tilt_max, psdx_tilt_min,psdx_tilt_sum, ...
   skewness_psdx, skewness_tilt_psdx, kurtosis_psdx ,kurtosis_tilt_psdx, dft_tilt_k_max_freq, ...
   dft_tilt_k_max_val,dft_samples_k_max_freq, dft_samples_k_max_val] = extract_dft_features( samplestest, nposfilestest,nnegfilestest,nbrOfSamples, target_freq , nbrfilestest);

lag = 30;
[cross_corr_max, sum_auto, min_auto, sum_pauto, min_pauto, auto_bins, auto_corr_flat, auto_corr, ...
    skewness_acor, kurtosis_acor, sum_changes_auto, mean_changes_auto, der_mean_auto_corr, ...
   der_max_auto_corr ,der_min_auto_corr, der_sum_auto_corr] = extract_corr_features(samplestest,nposfilestest,nnegfilestest,lag, nbrfilestest);

featureMatrix = [sum_auto(:,3) min_auto(:,2:3) meanFeatures([1],:)' ...
 minFeatures(2:3,:)' ...
maxFeatures(1:2,:)'  skewness_vec(:,2:3) kurtosis_acor(:,[1 3]) skewness_acor ...
sum_changes'  squeeze(psdx_peak_freq_bin_tilt([1],1,:)) squeeze(psdx_peak_freq_bin_tilt(:,3,:))'...
skewness_psdx psdx_nbrPeaks_tilt' ...
squeeze(psdx_peak_freq_bin([1 3 4 5],1,:))' squeeze(psdx_peak_freq_bin([1 5],2,:))' ...
index_of_first_max(3,:)' meanTiltFeatures(2,:)'  stdFeatures(2,:)' ...
sum_changes_auto(1:2,:)' ];

featureMatrix= featureMatrix - repmat(mean_train,size(featureMatrix,1),1);
featureMatrix = featureMatrix ./ repmat(std_train,size(featureMatrix,1),1);

[pred_labels_test_set,score_test_set] = predict(SVMModel,featureMatrix);
label = zeros(nposfilestest+nnegfilestest,1);
label(1:nposfilestest,1) = 1;

%Labels are the actual labels, pred_labels are the predictions made by the
%SVM model on the testset. Thus 
%pred_labels - label == 0 are correct predictions.
%pred_labels - label == 1. Are negatives that have been classified as pos
% pred_labels - label == -1. Are positives that have been classified as neg
res_test = pred_labels_test_set - label;
%size(label,1)-sum(label) = The amounts of negatives in the set.
false_positive_test = length(res_test(res_test(:)==1))/(size(label,1)-sum(label));
true_positive_test = 1 - length(res_test(res_test(:)==-1))/sum(label);
end

